name: My-First-Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Mesaag
              run: echo "My first Github Actions Job"
            - name: List files
              run: ls
            - name: Clone Repo 
              run:  git clone https://github.dev/imranshs08/action-01.git
            - name: Read File
              run: cat README.md
